name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: app/requirements.txt
      - run: |
          pip install -r app/requirements.txt
          pip install flake8 mypy
          flake8 app
          mypy app

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: app/requirements.txt
      - run: |
          pip install -r app/requirements.txt
          pip install black
          black --check app

  build:
    name: Build & Run
    needs: [lint, format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: app/requirements.txt
      - run: |
          pip install -r app/requirements.txt
          pip install uvicorn
          uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers 1 &
          sleep 5
          curl -f http://127.0.0.1:8000/ || exit 1